<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoIdeaScoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('demo_idea_scores')->insert([
            [
                'id' => '1',
                'problem' => 'The solution is meant to solve the issue of electronic waste and reduce the heap of idle electronic products in our homes',
                'solution'=>'"E waste has always been a growing problem in the world. The inclusion of circular economy techniques in our day to day life can bring about a huge change in this context. The consumer electronic goods that remains idle in our homes or is inoperative can be thought of as a means to implement the idea. If there exists a system which can collect the inoperative home consumer goods, extract the different parts like transistors, diodes, etc and make it to use in future products, I think it may reduce the problem of e waste marginally. Even if the parts are damaged, in some cases, trying to repair them can be much more cheap way than building a new component altogether. Thus even the manufacturing cost can be reduced. Also, there can be a quick supply of electronic components in the market.
There can also be a responsible framework of second hand consumer electronic goods. Thus even the poor people can afford the best of consumer electronics without spending much from their pocket. This will include more people in the consumer electronics market which can in turn improve the market forces."',
                'evidence'=>'7',
                'evidence_justification' => 'The idea is scientifically feasible but lacks actual data and quantitative measures.',
                'evidence_detail' => '"[""The dismantling and repair of electronic products for reuse is mechanically possible and is already widely practiced."",""While no specific scientific or experimental data was provided, the idea is grounded in established principles of recycling and electronics manufacturing."",""Still, a more detailed analysis comparing this method with traditional practices can help in assessing its actual efficiency and effectiveness.""]"',
                'impact'=>'8',
                'impact_justification' => '"Implementing this idea can positively impact the environment by reducing waste, although actual numeric measures are not provided."',
                'impact_detail' => '"[""By recycling and reusing parts from inoperative electronic goods, the amount of e-waste produced can be significantly reduced."",""It promotes the principles of a circular economy by ensuring that resources are not merely discarded, but reutilized, resulting in a reduction of resource consumption and thus leading to long-term sustainability."",""However, the process of collecting, disassembling, and repairing electronic components may entail additional environmental costs such as energy and carbon emissions during transport, and these factors need to be evaluated to get a more comprehensive overview of the environmental impact.""]"',
                'possible'=>'8',
                'possible_justification' => '"This idea has potential for societal acceptance, given the increasing awareness about sustainability, although practical hurdles need to be addressed."',
                'possible_detail' => '"[""The proposal to provide affordable second-hand electronic goods can be appealing to certain consumer groups especially in developing countries."",""However, the main barriers to this idea may involve implementation such as collection logistics, repairing facilities, and regulatory compliance regarding electronic waste management."",""Moreover, the perception towards second-hand goods varies across cultures and societies, and convincing consumers to trust the quality and reliability of these goods may pose a challenge. Creating awareness and robust quality control systems are key to gaining wider societal acceptance.""]"',
                'length' => '0',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '2',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '3',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '4',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '5',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '6',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '7',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '8',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '9',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '10',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '11',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],
            [
                'id' => '12',
                'problem' => '',
                'solution'=>'',
                'evidence'=>'',
                'evidence_justification' => '',
                'evidence_detail' => '',
                'impact'=>'',
                'impact_justification' => '',
                'impact_detail' => '',
                'possible'=>'',
                'possible_justification' => '',
                'possible_detail' => '',
                'length' => '',
                'note' => '',
                'created_at' => '',
                'updated_at' => ''
            ],

        ]);
    }
}
